enum FastenerStandard { metric, imperial }

class BoltSpec {
  final String size;
  final FastenerStandard standard;
  final double majorDiaMm;
  final String pitchOrTpi;
  final double tapDrillMm;
  final String tapDrillFraction;
  final double clearanceCloseMm;
  final double clearanceFreeMm;
  final String hexKeySize;

  const BoltSpec({
    required this.size,
    required this.standard,
    required this.majorDiaMm,
    required this.pitchOrTpi,
    required this.tapDrillMm,
    required this.tapDrillFraction,
    required this.clearanceCloseMm,
    required this.clearanceFreeMm,
    required this.hexKeySize,
  });

  static List<BoltSpec> get database => [
        // Metric Standards (ISO coarse)
        const BoltSpec(
          size: 'M2 x 0.4',
          standard: FastenerStandard.metric,
          majorDiaMm: 2.0,
          pitchOrTpi: '0.40 mm',
          tapDrillMm: 1.6,
          tapDrillFraction: '1.6mm / #52',
          clearanceCloseMm: 2.2,
          clearanceFreeMm: 2.4,
          hexKeySize: '1.5 mm',
        ),
        const BoltSpec(
          size: 'M2.5 x 0.45',
          standard: FastenerStandard.metric,
          majorDiaMm: 2.5,
          pitchOrTpi: '0.45 mm',
          tapDrillMm: 2.05,
          tapDrillFraction: '2.05mm / #45',
          clearanceCloseMm: 2.7,
          clearanceFreeMm: 3.0,
          hexKeySize: '2.0 mm',
        ),
        const BoltSpec(
          size: 'M3 x 0.5',
          standard: FastenerStandard.metric,
          majorDiaMm: 3.0,
          pitchOrTpi: '0.50 mm',
          tapDrillMm: 2.5,
          tapDrillFraction: '2.50mm / #39',
          clearanceCloseMm: 3.2,
          clearanceFreeMm: 3.4,
          hexKeySize: '2.5 mm',
        ),
        const BoltSpec(
          size: 'M4 x 0.7',
          standard: FastenerStandard.metric,
          majorDiaMm: 4.0,
          pitchOrTpi: '0.70 mm',
          tapDrillMm: 3.3,
          tapDrillFraction: '3.30mm / #30',
          clearanceCloseMm: 4.3,
          clearanceFreeMm: 4.5,
          hexKeySize: '3.0 mm',
        ),
        const BoltSpec(
          size: 'M5 x 0.8',
          standard: FastenerStandard.metric,
          majorDiaMm: 5.0,
          pitchOrTpi: '0.80 mm',
          tapDrillMm: 4.2,
          tapDrillFraction: '4.20mm / #19',
          clearanceCloseMm: 5.3,
          clearanceFreeMm: 5.5,
          hexKeySize: '4.0 mm',
        ),
        const BoltSpec(
          size: 'M6 x 1.0',
          standard: FastenerStandard.metric,
          majorDiaMm: 6.0,
          pitchOrTpi: '1.00 mm',
          tapDrillMm: 5.0,
          tapDrillFraction: '5.00mm / #9',
          clearanceCloseMm: 6.4,
          clearanceFreeMm: 6.6,
          hexKeySize: '5.0 mm',
        ),
        const BoltSpec(
          size: 'M8 x 1.25',
          standard: FastenerStandard.metric,
          majorDiaMm: 8.0,
          pitchOrTpi: '1.25 mm',
          tapDrillMm: 6.8,
          tapDrillFraction: '6.80mm / Letter H',
          clearanceCloseMm: 8.4,
          clearanceFreeMm: 9.0,
          hexKeySize: '6.0 mm',
        ),
        const BoltSpec(
          size: 'M10 x 1.5',
          standard: FastenerStandard.metric,
          majorDiaMm: 10.0,
          pitchOrTpi: '1.50 mm',
          tapDrillMm: 8.5,
          tapDrillFraction: '8.50mm / Letter R',
          clearanceCloseMm: 10.5,
          clearanceFreeMm: 11.0,
          hexKeySize: '8.0 mm',
        ),
        const BoltSpec(
          size: 'M12 x 1.75',
          standard: FastenerStandard.metric,
          majorDiaMm: 12.0,
          pitchOrTpi: '1.75 mm',
          tapDrillMm: 10.2,
          tapDrillFraction: '10.2mm / 13/32"',
          clearanceCloseMm: 13.0,
          clearanceFreeMm: 13.5,
          hexKeySize: '10.0 mm',
        ),

        // Imperial Standards (UNC / UNF)
        const BoltSpec(
          size: '#2-56 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 2.18,
          pitchOrTpi: '56 TPI',
          tapDrillMm: 1.80,
          tapDrillFraction: '#50 (0.0700")',
          clearanceCloseMm: 2.38,
          clearanceFreeMm: 2.50,
          hexKeySize: '5/64"',
        ),
        const BoltSpec(
          size: '#4-40 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 2.84,
          pitchOrTpi: '40 TPI',
          tapDrillMm: 2.25,
          tapDrillFraction: '#43 (0.0890")',
          clearanceCloseMm: 3.00,
          clearanceFreeMm: 3.20,
          hexKeySize: '3/32"',
        ),
        const BoltSpec(
          size: '#6-32 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 3.50,
          pitchOrTpi: '32 TPI',
          tapDrillMm: 2.75,
          tapDrillFraction: '#36 (0.1065")',
          clearanceCloseMm: 3.80,
          clearanceFreeMm: 4.00,
          hexKeySize: '7/64"',
        ),
        const BoltSpec(
          size: '#8-32 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 4.16,
          pitchOrTpi: '32 TPI',
          tapDrillMm: 3.45,
          tapDrillFraction: '#29 (0.1360")',
          clearanceCloseMm: 4.50,
          clearanceFreeMm: 4.80,
          hexKeySize: '9/64"',
        ),
        const BoltSpec(
          size: '#10-24 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 4.82,
          pitchOrTpi: '24 TPI',
          tapDrillMm: 3.80,
          tapDrillFraction: '#25 (0.1495")',
          clearanceCloseMm: 5.20,
          clearanceFreeMm: 5.50,
          hexKeySize: '5/32"',
        ),
        const BoltSpec(
          size: '1/4"-20 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 6.35,
          pitchOrTpi: '20 TPI',
          tapDrillMm: 5.10,
          tapDrillFraction: '#7 (0.2010")',
          clearanceCloseMm: 6.70,
          clearanceFreeMm: 7.10,
          hexKeySize: '3/16"',
        ),
        const BoltSpec(
          size: '5/16"-18 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 7.94,
          pitchOrTpi: '18 TPI',
          tapDrillMm: 6.60,
          tapDrillFraction: 'Letter F (0.2570")',
          clearanceCloseMm: 8.30,
          clearanceFreeMm: 8.70,
          hexKeySize: '1/4"',
        ),
        const BoltSpec(
          size: '3/8"-16 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 9.52,
          pitchOrTpi: '16 TPI',
          tapDrillMm: 8.00,
          tapDrillFraction: '5/16" (0.3125")',
          clearanceCloseMm: 9.90,
          clearanceFreeMm: 10.30,
          hexKeySize: '5/16"',
        ),
        const BoltSpec(
          size: '1/2"-13 UNC',
          standard: FastenerStandard.imperial,
          majorDiaMm: 12.70,
          pitchOrTpi: '13 TPI',
          tapDrillMm: 10.80,
          tapDrillFraction: '27/64" (0.4219")',
          clearanceCloseMm: 13.50,
          clearanceFreeMm: 14.00,
          hexKeySize: '3/8"',
        ),
      ];
}
